/*
 *  A utility function to get the user data from the server side
 */

import { User } from "@/payload-types";
import { ReadonlyRequestCookies } from "next/dist/server/web/spec-extension/adapters/request-cookies";
import { NextRequest } from "next/server";

export const getServerSideUser = async (
  cookies: NextRequest["cookies"] | ReadonlyRequestCookies
) => {
  // get the token value generated by payload stored as cookies
  const token = cookies.get("payload-token")?.value;

  // fetch the data of the logged in user or returns null
  // api endpoint from Payload where "users" is the collection name in our db
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_SERVER_URL}/api/users/me`,
    {
      headers: {
        // authenticate the user
        Authorization: `JWT ${token}`,
      },
    }
  );

  // extract the JSON content and give it a type of User from payload types or null
  const { user } = (await res.json()) as { user: User | null };

  return { user };
};
